[package]
name = "boring-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptoki = "0.6.1"
tokio = { version = "1.34.0", features = ["full"] }
once_cell = "1.19.0"
